configured_endpoints: 166
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/hiteshchoudhary-ssesph%2Ffreeapiapp-a9f3a290e4dc07d70270ba92440e0cace3c7015b2089349eba66608e8af6bbbf.yml
